[http]
  [http.routers]
    [http.routers.jellyfin]
      rule = "Host(`jellyfin.example.com`)"
      entrypoints = ["https"]
      service = "jellyfin"
      middlewares = ["chain-authelia"]
  [http.services]
    [http.services.jellyfin.loadBalancer]
      [[http.services.jellyfin.loadBalancer.servers]]
        url = "http://172.17.0.1:8096"
